# .github/workflows/javabuild.yml to trigger build

name: Build

on:
 workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashfiles('**pom.xml') }}

      - name: Build with Maven
        run: |
          mvn clean 
          mvn install

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.4.1
        with:
          name: jar
          path: target/*.jar

      - name: Configure Jfrog CLI
        uses: jfrog/setup-jfrog-cli@v4.5.6
        with:
           version: latest
        env:
           JF_URL: https://trialdeepademo.jfrog.io
           JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}

      # - name: Set up JFrog CLI
        # run: |
          # echo "Configuring JFrog CLI..."
          # jfrog config add my-jfrog-server \
            # --url=https://trialdeepademo.jfrog.io \
            # --user=${{ secrets.JFROG_USER }} \
            # --password=${{ secrets.JFROG_PASSWORD }} \
            # --interactive=false

      # - name: Upload JAR to JFrog
        # run: |
          # jfrog rt u "target/*.jar" "petjfrog-repo/" --server-id=my-jfrog-server

