# .github/workflows/sonar.yml updated check
name: Sonar Scan

on:
  workflow_call:

jobs:
  sonar:
    runs-on: ghactions-demo
    #needs: build  # Ensures Sonar runs after build succeeds
    steps:
      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.projectKey=deepakann_Devsecops_CI -Dsonar.organization=deepakann -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
